# Generated by Django 6.0.5 on 2026-06-25 16:50

import django.db.models.deletion
import oauth_mcp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0028_alter_org_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default=oauth_mcp.models._gen_client_id, max_length=128, unique=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('redirect_uris', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('redirect_uri', models.TextField()),
                ('code_challenge', models.CharField(max_length=255)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_mcp.oauthclient')),
            ],
        ),
    ]
