# Generated by Django 6.0.5 on 2026-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0012_alter_opportunity_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='offer_brand',
            field=models.CharField(choices=[('bluebee', 'BlueBee'), ('bespoke', 'BespokeSoft')], default='bespoke', help_text='Waypoint that selects the offer theme/branding (BlueBee dark / BespokeSoft light).', max_length=16, verbose_name='Offer Brand'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_id',
            field=models.IntegerField(blank=True, help_text='ID returned by the BlueBee offers API; used for follow-up edits.', null=True, verbose_name='Offer ID'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_status',
            field=models.CharField(blank=True, help_text='generated / editing / error', max_length=16, null=True, verbose_name='Offer Status'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_url',
            field=models.URLField(blank=True, help_text='Ready-to-send public link to the generated offer page.', max_length=500, null=True, verbose_name='Offer URL'),
        ),
    ]
