# Generated by Django 6.0.5 on 2026-06-28 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('opportunity', '0013_opportunity_offer_brand_opportunity_offer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='generated_offer',
            field=models.ForeignKey(blank=True, help_text='Native generated offer (Feature 4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='offer_id',
            field=models.IntegerField(blank=True, help_text='Legacy int id from the old bluebee.marketing proxy.', null=True, verbose_name='Offer ID (legacy)'),
        ),
    ]
