# Generated by Django 6.0.5 on 2026-06-28 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0028_alter_org_default_currency'),
        ('opportunity', '0013_opportunity_offer_brand_opportunity_offer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='Klient')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł oferty')),
                ('brand', models.CharField(choices=[('bluebee', 'BlueBee'), ('bespoke', 'BespokeSoft')], default='bespoke', max_length=16, verbose_name='Brand')),
                ('offer_data', models.JSONField(default=dict, verbose_name='Dane oferty')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłana'), ('viewed', 'Wyświetlona'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona')], default='draft', max_length=16, verbose_name='Status')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('access_token', models.CharField(blank=True, max_length=16, verbose_name='Access token')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Wysłano')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Pierwsze wyświetlenie')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Odpowiedź klienta')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Ważność do')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Wartość netto (PLN)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Wewnętrzne notatki')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='opportunity.opportunity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
                'db_table': 'offer',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-created_at'], name='offer_org_id_90efa4_idx'), models.Index(fields=['slug'], name='offer_slug_1f444e_idx')],
            },
        ),
    ]
