# Generated by Django 6.0.5 on 2026-06-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_alter_org_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='offer_accent',
            field=models.CharField(default='#E3FF04', help_text='Hex accent color (e.g. #0d6efd) driving offer links/headings/highlights.', max_length=9),
        ),
        migrations.AddField(
            model_name='org',
            name='offer_prepared_by',
            field=models.CharField(blank=True, help_text='Signature on offers; falls back to company_name / name when blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='org',
            name='offer_theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='Base palette for generated offer pages.', max_length=8),
        ),
    ]
